### PR TITLE
feat(openfga): use helm hooks to wait for migration

### PR DESCRIPTION
**Pull request by PedroArvela**
## Description

Instead of waiting for the migration job to finish in an init container, use Helm's native [Chart Hooks](https://helm.sh/docs/topics/charts_hooks/) to wait for the migration to finish before even starting to update the deployment.

This is a more robust approach that prevents, for example, a failed migration, from preventing old pods from coming up. This way, no deployment update is actually started, and old pods can continue being scheduled if required.

## Review Checklist
- [ ] I have clicked on ["allow edits by maintainers"](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [x] I have added documentation for new/changed functionality in this PR or in a PR to [openfga.dev](https://github.com/openfga/openfga.dev) [Provide a link to any relevant PRs in the references section above]
- [x] The correct base branch is being used, if not `main`
- [x] I have added tests to validate that the change in functionality is working as expected

### CODE REVIEW

**Comment by PedroArvela** [comment]
Another advantage of this is that it removes the need for the role and role binding to allow reading jobs, as that becomes a responsibility of Helm itself.

**Comment by jon-whit** [comment]
@PedroArvela It seems that this behavioral change would break some basic releases with the Helm chart. If I want to release OpenFGA with a Postgres database, for example

```
helm install openfga openfga/openfga \
  --set datastore.engine=postgres \
  --set datastore.uri="postgres://postgres:password@openfga-postgresql.default.svc.cluster.local:5432/postgres?sslmode=disable" \
  --set postgres.enabled=true \
  --set postgresql.auth.postgresPassword=password \
  --set postgresql.auth.database=postgres
```
then these changes proposed herein will attempt to run the migration job before the database is even online. The reason we've modeled the migration process as a job + an init container is so that the database has time to come up and be online before we attempt to apply the migration job.

Is there something I'm missing? I think this approach would be nice if we assume the database is already running, and we simply want to gate the OpenFGA deployment until the migration pre-install hook is complete, but for  standalone deployments where you are deploying the database as well, then this approach has some side-effects.

**Review by jon-whit — CHANGES_REQUESTED** [review]
I left a comment ☝️  that indicates some complications with these changes. Please take a look 👍

**Comment by PedroArvela** [comment]
I completely forgot about the embedded database conflicting with this.

I get it a quick search, and it seems indeed it's not possible to set up a hook to go after the DB dependency is up and running, but before the deployment is updated.

I don't think there's an easy way to consolidate this approach with the standalone installation.

Unless there is a way you can think of to make it work, I think we can close this PR

**Comment by jon-whit** [comment]
> I completely forgot about the embedded database conflicting with this.
> 
> I get it a quick search, and it seems indeed it's not possible to set up a hook to go after the DB dependency is up and running, but before the deployment is updated.
> 
> I don't think there's an easy way to consolidate this approach with the standalone installation.
> 
> Unless there is a way you can think of to make it work, I think we can close this PR

Yeah, I wish we could use Helm pre-install hooks for this use case, but unfortunately I don't see it as a viable option. If you're using the chart for a standalone installation (which some of our documentation refers to), then this will impact those examples etc..

I'll close for now and if we get enough feedback from the community indicating this behavior would be preferable, then we can resurrect this work 👍 . Thanks for the contribution though @PedroArvela . We really appreciate it!

**Pull request closed without merging**
