### PR TITLE
fix(job): add node configuration settings to job pod as well

### PR DESCRIPTION
**Pull request by jakereps**
Pass tolerations, affinity, and nodeSelector configuration along to the job definition.

## Description

Current configuration does not allow specifying tolerations on the job config, resulting in the deployment pods, but never the job pod being scheduled on infra that requires taint tolerations. This PR adds three existing node configuration items to the job definition as well, so both are controlled in the same manner.

Personally, I only need tolerations but the others seemed like they could/should be shared so I carried over all three.

## References

N/A

## Review Checklist
- [x] I have clicked on ["allow edits by maintainers"](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [ ] I have added documentation for new/changed functionality in this PR or in a PR to [openfga.dev](https://github.com/openfga/openfga.dev) [Provide a link to any relevant PRs in the references section above]
  - None of the values being added to the job definition appear to exist in the values schema, so I wasn't sure whether to add them or not, let me know and I can add any docs needed!
- [x] The correct base branch is being used, if not `main`
- [ ] I have added tests to validate that the change in functionality is working as expected

### CODE REVIEW

**Comment by jakereps** [comment]
Just as a note, I wasn’t really sure if it was worth creating separate values specifically for migrations as it already has a top level key to use, so it’d be `migrate.tolerations` instead, or if it’s reasonable to apply the root level ones that already existed to “all” definitions.

**Comment by jakereps** [comment]
Hey, just giving a gentle bump on this one for review/feedback. Thanks!

**Comment by rhamzeh** [comment]
Apologies for the delay @jakereps - we're taking a look

**Review by jpadilla — APPROVED** [review]

**Comment by rhamzeh** [comment]
Thanks for your PR @jakereps!

**Pull request merged**
