### PR TITLE
feat: add extraObjects 

### PR DESCRIPTION
**Pull request by danielloader**
Adding arbitrary manifests to the helm chart 

## Description

I'd like to be able to deploy other resources not included in the chart; Gateway HTTPRoutes, CloudnativePG Clusters etc.

## References

- [Based on the prior art from ArgoCD](https://github.com/argoproj/argo-helm/blob/8b02b6d9b828902ba0d9ae1e6ddb4f060a5975ca/charts/argo-cd/values.yaml#L564-L591) - https://github.com/argoproj/argo-helm/blob/8b02b6d9b828902ba0d9ae1e6ddb4f060a5975ca/charts/argo-cd/templates/extra-manifests.yaml

## Review Checklist
- [x] I have clicked on ["allow edits by maintainers"](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [x] I have added documentation for new/changed functionality in this PR or in a PR to [openfga.dev](https://github.com/openfga/openfga.dev) [Provide a link to any relevant PRs in the references section above]
- [x] The correct base branch is being used, if not `main`
- [x] I have added tests to validate that the change in functionality is working as expected

### CODE REVIEW

**Comment by wenzel-felix** [comment]
@rhamzeh / @jon-whit, could you please review this PR. The changes here do not negatively impact the chart generally, but it would allow for more flexible deployments like other charts offer as well (eg. creating related secret provider classes for the Postgres uri secret).
Thanks

**Review by rhamzeh — APPROVED** [review]
Thanks @danielloader!

**Comment by danielloader** [comment]
Anything else I need to do to get this merged in and released?
Thanks

**Comment by danielloader** [comment]
Attempted to fix the lint failure by adding a schema entry, awaiting approval to test.

**Review by rhamzeh — APPROVED** [review]

**Pull request merged**
