### PR TITLE
feat: added hook to job to delete/recreate during upgrade/rollback

### PR DESCRIPTION
**Pull request by jliedy**
Added annotations to the job in order for the migration job to be deleted after a successful run.

## Description

In reference to Issue #69 I've added hook annotations to the migration job in order for the job to be deleted and then recreated during a helm upgrade/rollback.

## References

For views on how to add hooks to jobs, one can reference the Helm documentation at: https://helm.sh/docs/topics/charts_hooks/

## Review Checklist
- [x] I have clicked on ["allow edits by maintainers"](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [x] I have added documentation for new/changed functionality in this PR or in a PR to [openfga.dev](https://github.com/openfga/openfga.dev) [Provide a link to any relevant PRs in the references section above]
- [x] The correct base branch is being used, if not `main`
- [x] I have added tests to validate that the change in functionality is working as expected

### CODE REVIEW

**Comment by jliedy** [comment]
I've noticed something awkward when deleting a job before the deployment can init is causing the k8s-wait-for initcontainer to not start if you're using v1.7 or later.  Gonna see what I can figure out.

**Comment by jliedy** [comment]
Found an issue that by doing this, the job doesn't use the latest image, but the previously deployed one.

**Comment by jliedy** [comment]
This solution still isn't my favorite.  If you deploy with helm using the `--wait` flag, it will cause the deploy process to fail as the deployment won't start until the migration job runs, and the migration job won't get applied until the deployment succeeds.

**Comment by jliedy** [comment]
I've gotten this style to work fairly consistently with a separate helm chart that I manage.  Able to consistently deploy and update without issue.

**Comment by jon-whit** [comment]
@jliedy sorry this one has fallen through the cracks. We've been heads down working on some big features in the core OpenFGA server. Would you mind rebasing on `main` and we can take a final look!

🙇

**Comment by jliedy** [comment]
I've had my head down in some stuff myself, but we've been running in openshift what I've suggested with the change here.  I'll try to get back to this this week with an update.

**Comment by jon-whit** [comment]
@jliedy just following up? Any updates/progress since our last chat?

**Comment by jliedy** [comment]
Sorry, no, I stink.  Had some personal things that needed to be taken care of.

Lemme go ahead and get cracking on this now.

**Comment by jliedy** [comment]
This wasn't supposed to be closed.

**Comment by jliedy** [comment]
I think it's ready to be reviewed.  Let me know if you'd prefer me to add the job migration annotations for the helm hooks to the values.yaml file instead of the job.yaml file.

**Comment by rhamzeh** [comment]
Thanks! Will refer to the team for review

**Comment by jon-whit** [comment]
> I think it's ready to be reviewed. Let me know if you'd prefer me to add the job migration annotations for the helm hooks to the values.yaml file instead of the job.yaml file.

@jliedy everything looks good, but I think this would be a good idea as it is more extensible. If you are using the chart and you wish not to have these hooks, then that should be overridable with the values. Mind making that change real quick and then we can merge.

**Comment by jliedy** [comment]
Yeah, I could make an argument for it either way so I figured I'd put the option out there.

Done.

**Review by jon-whit — APPROVED** [review]

**Pull request merged**
