### PR TITLE
chore(lint): add values.schema.json validation strict

### PR DESCRIPTION
**Pull request by jon-whit**
## Description
Add `additionalProperties: false` to the top level `values.schema.json` specification so that we avoid introducing new values into the `values.yaml` file without having explicit documentation for it.

As part of ☝️ it was brought to my attention that we didn't have some of the common Helm chart values specified in the `values.schema.json`, so coverage has been added for those undocumented values.

## References
Added entries for the top-level subchart properties to the `values.schema.json` file so we can do `additionalProperties: false` and still pass the Helm linter. See https://github.com/helm/helm/issues/10392 for more info.

## Review Checklist
- [x] I have clicked on ["allow edits by maintainers"](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [x] I have added documentation for new/changed functionality in this PR or in a PR to [openfga.dev](https://github.com/openfga/openfga.dev) [Provide a link to any relevant PRs in the references section above]
- [x] The correct base branch is being used, if not `main`
- [x] I have added tests to validate that the change in functionality is working as expected

### CODE REVIEW

**Comment by jpadilla** [comment]
@jon-whit when this is ready to get merged, can we bump openfga to v1.4.0?

**Review by rhamzeh — COMMENTED** [review]
Is the initContainer change breaking?

**Comment by jon-whit** [comment]
> Is the initContainer change breaking?

It is, _but_ the prior values definition seems quite misleading. The `migrations` job image isn't the `k8s-wait-for` image, that's the init container image for the migrations job. So that yaml definition, to me, was quite misleading.

**Comment by rhamzeh** [comment]
@jon-whit - yeah the new way may be better, but let's document that in the release notes, because anyone who was previously working with it will now have to update to a different config

**Review by jpadilla — APPROVED** [review]

**Pull request merged**
